services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    depends_on:
      - database
      - mailhog
    environment:
      MAILER_DSN: smtp://mailhog:1025



  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: app-mailer
    ports:
      - "8025:8025"    # веб-інтерфейс
      - "1025:1025"    # SMTP

  database:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  worker:
    build:
      context: .
    command: php bin/console messenger:consume async -vv
    depends_on:
      - php
      - database
    volumes:
      - .:/app


volumes:
  db_data:

